version: "3" #docker version 3 사용
services: #service들 정의
    application:
        container_name: chatting-app
        image: chatting
        build:
            . #image를 DockerFile 기반으로 사용한다
            # dockerfile: ./Dockerfile #기존에 설정해둔 DockerFile을 지정히여 build 된 jar 파일을 container에 올린다.
        restart: always #컨테이너 재실행
        # depends_on: #database service가 실행된 이후에 실행
        # - redis
        ports:
            - 8085:8085
        # environment: #환경 설정(database연결 및 profile 지정)
        networks:
            - redis-network
        external_links:
            - redis
        environment:
            SPRING_REDIS_HOST: redis_boot
            SPRING_REDIS_PORT: 6379
        depends_on:
            - redis

    redis:
        image: redis:alpine
        # command: redis-server --port 6379
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        container_name: redis_boot
        hostname: redis
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - 6379:6379
        restart: always
        networks:
            - redis-network

networks: #네트워크 설정
    redis-network:
#docker-compose up --build
